# Generated by Django 3.2.6 on 2023-01-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230124_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car',
            field=models.ManyToManyField(to='users.Car', verbose_name='carros del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('R', 'Reviewed'), ('A', 'Accepted'), ('E', 'Error'), ('N', 'Not Reviewed')], max_length=1),
        ),
    ]
