# Generated by Django 3.2.6 on 2023-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230124_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='car',
            new_name='cars',
        ),
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('A', 'Accepted'), ('R', 'Reviewed'), ('N', 'Not Reviewed')], max_length=1),
        ),
    ]
