# Generated by Django 3.2.6 on 2023-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230124_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['rating'], 'verbose_name': 'Sitio Web', 'verbose_name_plural': 'Sitios Web'},
        ),
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('R', 'Reviewed'), ('N', 'Not Reviewed'), ('A', 'Accepted')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='website',
            table='website_custom_table_name',
        ),
    ]
