# Generated by Django 3.2.6 on 2023-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230124_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('N', 'Not Reviewed'), ('E', 'Error'), ('R', 'Reviewed')], max_length=1),
        ),
    ]
