# Generated by Django 3.2.6 on 2023-01-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_website_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('R', 'Reviewed'), ('A', 'Accepted'), ('N', 'Not Reviewed')], max_length=1),
        ),
    ]
