# Generated by Django 3.2.6 on 2023-01-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_website_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('N', 'Not Reviewed'), ('R', 'Reviewed'), ('A', 'Accepted'), ('E', 'Error')], max_length=1),
        ),
    ]
